version: '3.8'

services:
  watch:
    image: node:17-alpine
    volumes:
      - $PWD:/gravity
    working_dir: /gravity
    command: npx tsc --build src --watch --preserveWatchOutput
  http:
    image: nginx:alpine
    volumes:
      - $PWD:/usr/share/nginx/html
      - $PWD/nginx:/etc/nginx/templates
    ports:
      - "80:80"
